name: Build and Push Docker Image

on:
  push:  
    branches: ssh-local-deploy-actions
    paths: 
      - 'html/index.html' # this action will be executed when the index.html file is updated

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout the repo content
        uses: actions/checkout@v4 
        
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to docker hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gabi1447/nginx-actions:${{ github.sha }}
      
      - name: Establishing SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP_VM }}
          username: ${{ secrets.USERNAME_VM }}
          key: ${{ secrets.P_KEY_VM }}
          port: ${{ secrets.PORT_VM }}
          script: |
            docker stop actions-docker
            docker rm actions-docker
            docker pull gabi1447/nginx-actions:${{ github.sha }} 
            docker run -d --name actions-docker -p 8081:80 gabi1447/nginx-actions:${{ github.sha }}