name: Build and Push Docker Image

on:
  push:  # Trigger on push events to the repository

jobs:
  build-and-push:
    runs-on: self-hosted  # Replace with your desired runner OS
    steps:
      - uses: actions/checkout@v4  # Checkout the repository code

      - name: Login to Docker Hub (replace with your credentials)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t gabi1447/custom-nginx .  

      - name: Push Docker image to Docker Hub
        run: docker push gabi1447/custom-nginx:${{ github.sha }}  

